export const data = [
	{
		id: 1,
		title: 'Буры',
		img: '/catalog/bur.webp',
		alt: 'Прокат Буры',
	},
	{
		id: 2,
		title: 'Виброплиты',
		img: '/catalog/vibroplita.webp',
		alt: 'Прокат Виброплиты',
	},
	{
		id: 3,
		title: 'Генераторы',
		img: '/catalog/generator.webp',
		alt: 'Прокат Генераторы',
	},
	{
		id: 4,
		title: 'Трамбовки',
		img: '/catalog/trambovka.webp',
		alt: 'Прокат Трамбовки',
	},
	{
		id: 5,
		title: 'Бетономешалки (бетоносмесители)',
		img: '/catalog/betonomashalka.webp',
		alt: 'Прокат Бетономешалки (бетоносмесители)',
	},
	{
		id: 6,
		title: 'Бензорезы',
		img: '/catalog/binzorez.webp',
		alt: 'Прокат Бензорезы',
	},
	{
		id: 7,
		title: 'Угловые шлифмашинки (Болгарки)',
		img: '/catalog/balgarka.webp',
		alt: 'Прокат Угловые шлифмашинки (Болгарки)',
	},
	{
		id: 8,
		title: 'Дрели',
		img: '/catalog/drel.webp',
		alt: 'Прокат Дрели',
	},
	{
		id: 9,
		title: 'Строительные фены',
		img: '/catalog/fen.webp',
		alt: 'Прокат Строительные фены',
	},
	{
		id: 10,
		title: 'Газонокасилки',
		img: '/catalog/gazonokasilka.webp',
		alt: 'Прокат Газонокасилки',
	},
	{
		id: 11,
		title: 'Культиваторы',
		img: '/catalog/kultivtor.webp',
		alt: 'Прокат Культиваторы',
	},
	{
		id: 12,
		title: 'Лестницы, стремянки',
		img: '/catalog/lestnici.webp',
		alt: 'Прокат Лестницы, стремянки',
	},
	{
		id: 13,
		title: 'Электролобзики',
		img: '/catalog/lobzik.webp',
		alt: 'Прокат Электролобзики',
	},
	{
		id: 14,
		title: 'Высечные ножницы',
		img: '/catalog/nozhnici.webp',
		alt: 'Прокат Высечные ножницы',
	},
	{
		id: 15,
		title: 'Отбойные молотоки',
		img: '/catalog/otboinik.webp',
		alt: 'Прокат Отбойные молотоки',
	},
	{
		id: 16,
		title: 'Перфораторы',
		img: '/catalog/perforator.webp',
		alt: 'Прокат Перфораторы',
	},
	{
		id: 17,
		title: 'Торцовочные пилы',
		img: '/catalog/pila.webp',
		alt: 'Прокат Торцовочные пилы',
	},
	{
		id: 18,
		title: 'Строительные пылесосы',
		img: '/catalog/pilesos.webp',
		alt: 'Прокат Строительные пылесосы',
	},
	{
		id: 19,
		title: 'Монтажные пистолеты',
		img: '/catalog/pistolet.webp',
		alt: 'Прокат Монтажные пистолеты',
	},
	{
		id: 20,
		title: 'Плиткорезы',
		img: '/catalog/plitkorez.webp',
		alt: 'Прокат Плиткорезы',
	},
	{
		id: 21,
		title: 'Шлифмашины',
		img: '/catalog/shlifmashinka.webp',
		alt: 'Прокат Шлифмашины',
	},
	{
		id: 22,
		title: 'Штроборезы',
		img: '/catalog/shtroborez.webp',
		alt: 'Прокат Штроборезы',
	},
	{
		id: 23,
		title: 'Шуруповерты',
		img: '/catalog/shurupovert.webp',
		alt: 'Прокат Шуруповерты',
	},
	{
		id: 24,
		title: 'Сварочные аппараты',
		img: '/catalog/svaroniy.webp',
		alt: 'Прокат Сварочные аппараты',
	},
	{
		id: 25,
		title: 'Тачки строительные и тележки',
		img: '/catalog/tachka.webp',
		alt: 'Прокат Тачки строительные и тележки',
	},
	
	{
		id: 26,
		title: 'Лазерные уровени',
		img: '/catalog/uroven.webp',
		alt: 'Прокат Лазерные уровни',
	},
]